# Generated by Django 4.2.30 on 2026-06-09 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Clima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('ruc', models.CharField(blank=True, max_length=20)),
                ('razon_social', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('tipo', models.CharField(blank=True, max_length=100)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Explosivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='GrupoPerforacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Labor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('titulo', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('letra', models.CharField(max_length=10)),
                ('nombre', models.CharField(blank=True, max_length=150)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'indexes': [models.Index(fields=['codigo'], name='catalogos_z_codigo_2d5c00_idx'), models.Index(fields=['is_active'], name='catalogos_z_is_acti_79acb9_idx'), models.Index(fields=['updated_at'], name='catalogos_z_updated_ea13dd_idx')],
            },
        ),
        migrations.CreateModel(
            name='UnidadMedida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['codigo'], name='catalogos_u_codigo_46e5be_idx'), models.Index(fields=['is_active'], name='catalogos_u_is_acti_8d9f40_idx'), models.Index(fields=['updated_at'], name='catalogos_u_updated_691708_idx')],
            },
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('cruza_medianoche', models.BooleanField(default=False)),
            ],
            options={
                'indexes': [models.Index(fields=['codigo'], name='catalogos_t_codigo_2c3e9c_idx'), models.Index(fields=['is_active'], name='catalogos_t_is_acti_6d8a70_idx'), models.Index(fields=['updated_at'], name='catalogos_t_updated_41f7c7_idx')],
            },
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('codigo', models.CharField(blank=True, max_length=50, null=True)),
                ('dni', models.CharField(blank=True, max_length=20, null=True)),
                ('nombres', models.CharField(max_length=150)),
                ('apellidos', models.CharField(max_length=150)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('es_ingeniero_minero', models.BooleanField(default=False)),
                ('es_supervisor', models.BooleanField(default=False)),
                ('es_operador', models.BooleanField(default=False)),
                ('cargo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trabajadores', to='catalogos.cargo')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trabajadores', to='catalogos.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['codigo'], name='catalogos_p_codigo_60c647_idx'), models.Index(fields=['is_active'], name='catalogos_p_is_acti_ece709_idx'), models.Index(fields=['updated_at'], name='catalogos_p_updated_8af22e_idx')],
            },
        ),
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('numero', models.IntegerField()),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'indexes': [models.Index(fields=['codigo'], name='catalogos_n_codigo_d07542_idx'), models.Index(fields=['is_active'], name='catalogos_n_is_acti_c60a3d_idx'), models.Index(fields=['updated_at'], name='catalogos_n_updated_88a528_idx')],
            },
        ),
        migrations.CreateModel(
            name='LaborFrente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('titulo', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True)),
                ('labor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='frentes', to='catalogos.labor')),
                ('nivel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='frentes', to='catalogos.nivel')),
                ('zona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='frentes', to='catalogos.zona')),
            ],
        ),
        migrations.AddField(
            model_name='labor',
            name='nivel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='labores', to='catalogos.nivel'),
        ),
        migrations.AddField(
            model_name='labor',
            name='zona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='labores', to='catalogos.zona'),
        ),
        migrations.CreateModel(
            name='InsumoAccesorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True)),
                ('unidad_medida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='insumos_accesorios', to='catalogos.unidadmedida')),
            ],
        ),
        migrations.CreateModel(
            name='Guardia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['codigo'], name='catalogos_g_codigo_b4808a_idx'), models.Index(fields=['is_active'], name='catalogos_g_is_acti_6ddd77_idx'), models.Index(fields=['updated_at'], name='catalogos_g_updated_72905c_idx')],
            },
        ),
        migrations.CreateModel(
            name='GrupoPerforacionIntegrante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('rol_en_grupo', models.CharField(blank=True, max_length=100)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrantes', to='catalogos.grupoperforacion')),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grupos_perforacion', to='catalogos.trabajador')),
            ],
        ),
        migrations.AddIndex(
            model_name='grupoperforacion',
            index=models.Index(fields=['codigo'], name='catalogos_g_codigo_0f8bc8_idx'),
        ),
        migrations.AddIndex(
            model_name='grupoperforacion',
            index=models.Index(fields=['is_active'], name='catalogos_g_is_acti_437ca7_idx'),
        ),
        migrations.AddIndex(
            model_name='grupoperforacion',
            index=models.Index(fields=['updated_at'], name='catalogos_g_updated_7c57a7_idx'),
        ),
        migrations.AddField(
            model_name='explosivo',
            name='unidad_medida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='explosivos', to='catalogos.unidadmedida'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='equipos', to='catalogos.empresa'),
        ),
        migrations.AddIndex(
            model_name='empresa',
            index=models.Index(fields=['codigo'], name='catalogos_e_codigo_47dda4_idx'),
        ),
        migrations.AddIndex(
            model_name='empresa',
            index=models.Index(fields=['is_active'], name='catalogos_e_is_acti_87fe0e_idx'),
        ),
        migrations.AddIndex(
            model_name='empresa',
            index=models.Index(fields=['updated_at'], name='catalogos_e_updated_e1d5fc_idx'),
        ),
        migrations.AddIndex(
            model_name='clima',
            index=models.Index(fields=['codigo'], name='catalogos_c_codigo_2169bb_idx'),
        ),
        migrations.AddIndex(
            model_name='clima',
            index=models.Index(fields=['is_active'], name='catalogos_c_is_acti_5544f4_idx'),
        ),
        migrations.AddIndex(
            model_name='clima',
            index=models.Index(fields=['updated_at'], name='catalogos_c_updated_abfd91_idx'),
        ),
        migrations.AddIndex(
            model_name='cargo',
            index=models.Index(fields=['codigo'], name='catalogos_c_codigo_aa4526_idx'),
        ),
        migrations.AddIndex(
            model_name='cargo',
            index=models.Index(fields=['is_active'], name='catalogos_c_is_acti_a999dd_idx'),
        ),
        migrations.AddIndex(
            model_name='cargo',
            index=models.Index(fields=['updated_at'], name='catalogos_c_updated_52ad5b_idx'),
        ),
        migrations.AddIndex(
            model_name='area',
            index=models.Index(fields=['codigo'], name='catalogos_a_codigo_ca38a7_idx'),
        ),
        migrations.AddIndex(
            model_name='area',
            index=models.Index(fields=['is_active'], name='catalogos_a_is_acti_ae1950_idx'),
        ),
        migrations.AddIndex(
            model_name='area',
            index=models.Index(fields=['updated_at'], name='catalogos_a_updated_5edc7f_idx'),
        ),
        migrations.AddIndex(
            model_name='trabajador',
            index=models.Index(fields=['codigo'], name='catalogos_t_codigo_3cf2a4_idx'),
        ),
        migrations.AddIndex(
            model_name='trabajador',
            index=models.Index(fields=['dni'], name='catalogos_t_dni_067799_idx'),
        ),
        migrations.AddIndex(
            model_name='trabajador',
            index=models.Index(fields=['is_active'], name='catalogos_t_is_acti_7b0112_idx'),
        ),
        migrations.AddIndex(
            model_name='trabajador',
            index=models.Index(fields=['updated_at'], name='catalogos_t_updated_e27bb4_idx'),
        ),
        migrations.AddIndex(
            model_name='laborfrente',
            index=models.Index(fields=['codigo'], name='catalogos_l_codigo_9ac3d5_idx'),
        ),
        migrations.AddIndex(
            model_name='laborfrente',
            index=models.Index(fields=['is_active'], name='catalogos_l_is_acti_76c22e_idx'),
        ),
        migrations.AddIndex(
            model_name='laborfrente',
            index=models.Index(fields=['updated_at'], name='catalogos_l_updated_925a61_idx'),
        ),
        migrations.AddIndex(
            model_name='labor',
            index=models.Index(fields=['codigo'], name='catalogos_l_codigo_7b6d92_idx'),
        ),
        migrations.AddIndex(
            model_name='labor',
            index=models.Index(fields=['is_active'], name='catalogos_l_is_acti_e14fe7_idx'),
        ),
        migrations.AddIndex(
            model_name='labor',
            index=models.Index(fields=['updated_at'], name='catalogos_l_updated_8c363e_idx'),
        ),
        migrations.AddIndex(
            model_name='insumoaccesorio',
            index=models.Index(fields=['codigo'], name='catalogos_i_codigo_368544_idx'),
        ),
        migrations.AddIndex(
            model_name='insumoaccesorio',
            index=models.Index(fields=['is_active'], name='catalogos_i_is_acti_3684db_idx'),
        ),
        migrations.AddIndex(
            model_name='insumoaccesorio',
            index=models.Index(fields=['updated_at'], name='catalogos_i_updated_c8705d_idx'),
        ),
        migrations.AddIndex(
            model_name='grupoperforacionintegrante',
            index=models.Index(fields=['is_active'], name='catalogos_g_is_acti_5dc9e6_idx'),
        ),
        migrations.AddIndex(
            model_name='grupoperforacionintegrante',
            index=models.Index(fields=['updated_at'], name='catalogos_g_updated_c7117f_idx'),
        ),
        migrations.AddConstraint(
            model_name='grupoperforacionintegrante',
            constraint=models.UniqueConstraint(fields=('grupo', 'trabajador'), name='uq_grupo_perforacion_trabajador'),
        ),
        migrations.AddIndex(
            model_name='explosivo',
            index=models.Index(fields=['codigo'], name='catalogos_e_codigo_98a6fa_idx'),
        ),
        migrations.AddIndex(
            model_name='explosivo',
            index=models.Index(fields=['is_active'], name='catalogos_e_is_acti_ff1b3f_idx'),
        ),
        migrations.AddIndex(
            model_name='explosivo',
            index=models.Index(fields=['updated_at'], name='catalogos_e_updated_d52d37_idx'),
        ),
        migrations.AddIndex(
            model_name='equipo',
            index=models.Index(fields=['codigo'], name='catalogos_e_codigo_7356b4_idx'),
        ),
        migrations.AddIndex(
            model_name='equipo',
            index=models.Index(fields=['is_active'], name='catalogos_e_is_acti_ee1b34_idx'),
        ),
        migrations.AddIndex(
            model_name='equipo',
            index=models.Index(fields=['updated_at'], name='catalogos_e_updated_b38fb3_idx'),
        ),
    ]
