# Generated by Django 4.2.30 on 2026-07-06 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['codigo'], name='catalogos_s_codigo_2fa37e_idx'), models.Index(fields=['is_active'], name='catalogos_s_is_acti_92ee44_idx'), models.Index(fields=['updated_at'], name='catalogos_s_updated_a0a091_idx')],
            },
        ),
        migrations.CreateModel(
            name='RequerimientoRubro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['codigo'], name='catalogos_r_codigo_8ea42d_idx'), models.Index(fields=['is_active'], name='catalogos_r_is_acti_ae5988_idx'), models.Index(fields=['updated_at'], name='catalogos_r_updated_b7ea3b_idx')],
            },
        ),
        migrations.CreateModel(
            name='RequerimientoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True)),
                ('seccion', models.CharField(choices=[('herramientas_otros', 'Herramientas y/o otros'), ('equipo_proteccion_personal', 'Equipo de proteccion personal')], max_length=40)),
                ('rubro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos_requerimiento', to='catalogos.requerimientorubro')),
                ('unidad_medida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='productos_requerimiento', to='catalogos.unidadmedida')),
            ],
            options={
                'indexes': [models.Index(fields=['codigo'], name='catalogos_r_codigo_ee8cd9_idx'), models.Index(fields=['seccion'], name='catalogos_r_seccion_378eb6_idx'), models.Index(fields=['rubro'], name='catalogos_r_rubro_i_879a54_idx'), models.Index(fields=['is_active'], name='catalogos_r_is_acti_7925a3_idx'), models.Index(fields=['updated_at'], name='catalogos_r_updated_b73baa_idx')],
            },
        ),
    ]
