# Generated by Django 4.2.30 on 2026-07-06 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0002_sucursal_requerimientorubro_requerimientoproducto'),
        ('mina', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartillaoperacionmina',
            name='responsable_requerimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cartillas_requerimiento_productos', to='catalogos.trabajador'),
        ),
        migrations.AddField(
            model_name='cartillaoperacionmina',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cartillas_requerimiento_productos', to='catalogos.sucursal'),
        ),
        migrations.AlterField(
            model_name='cartillaoperacionmina',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cartillas_mina', to='catalogos.area'),
        ),
        migrations.AlterField(
            model_name='cartillaoperacionmina',
            name='guardia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cartillas_mina', to='catalogos.guardia'),
        ),
        migrations.AlterField(
            model_name='cartillaoperacionmina',
            name='turno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cartillas_mina', to='catalogos.turno'),
        ),
        migrations.CreateModel(
            name='CartillaRequerimientoProductoDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('row_key', models.CharField(max_length=64)),
                ('seccion', models.CharField(choices=[('herramientas_otros', 'Herramientas y/o otros'), ('equipo_proteccion_personal', 'Equipo de proteccion personal')], max_length=40)),
                ('fecha', models.DateField()),
                ('descripcion', models.TextField(blank=True)),
                ('cantidad', models.DecimalField(decimal_places=3, max_digits=12)),
                ('prioridad', models.CharField(choices=[('BAJA', 'Baja'), ('ALTA', 'Alta')], default='BAJA', max_length=10)),
                ('cartilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requerimiento_productos', to='mina.cartillaoperacionmina')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requerimientos_cartilla', to='catalogos.requerimientoproducto')),
                ('rubro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requerimientos_cartilla', to='catalogos.requerimientorubro')),
                ('unidad_medida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requerimientos_productos', to='catalogos.unidadmedida')),
            ],
            options={
                'indexes': [models.Index(fields=['seccion'], name='mina_cartil_seccion_032c71_idx'), models.Index(fields=['fecha'], name='mina_cartil_fecha_d52cb9_idx'), models.Index(fields=['rubro'], name='mina_cartil_rubro_i_ec602c_idx'), models.Index(fields=['producto'], name='mina_cartil_product_676bb6_idx'), models.Index(fields=['prioridad'], name='mina_cartil_priorid_cf58bc_idx'), models.Index(fields=['updated_at'], name='mina_cartil_updated_7e0663_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='cartillarequerimientoproductodetalle',
            constraint=models.UniqueConstraint(fields=('cartilla', 'row_key'), name='uq_req_producto_cartilla_row'),
        ),
    ]
