# Generated by Django 4.2.30 on 2026-06-09 16:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoCartilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('schema_json', models.TextField(blank=True, default='{}')),
            ],
            options={
                'indexes': [models.Index(fields=['codigo'], name='cartillas_t_codigo_338362_idx'), models.Index(fields=['is_active'], name='cartillas_t_is_acti_4f7870_idx'), models.Index(fields=['updated_at'], name='cartillas_t_updated_08c9ab_idx')],
            },
        ),
        migrations.CreateModel(
            name='AsignacionCartillaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=20)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tipo_cartilla', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones_usuario', to='cartillas.tipocartilla')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_cartilla_mina', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['estado'], name='cartillas_a_estado_2c377a_idx'), models.Index(fields=['updated_at'], name='cartillas_a_updated_6e66bc_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='asignacioncartillausuario',
            constraint=models.UniqueConstraint(fields=('user', 'tipo_cartilla'), name='uq_asignacion_cartilla_usuario'),
        ),
    ]
