# Generated by Django 4.2.30 on 2026-06-09 16:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mina', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('client_attachment_id', models.CharField(max_length=64)),
                ('module_key', models.CharField(max_length=100)),
                ('row_key', models.CharField(blank=True, max_length=64)),
                ('slot', models.PositiveIntegerField(blank=True, null=True)),
                ('file', models.FileField(upload_to='attachments/%Y/%m/%d/')),
                ('original_name', models.CharField(blank=True, max_length=255)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('size', models.PositiveBigIntegerField(blank=True, null=True)),
                ('cartilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='mina.cartillaoperacionmina')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mina_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['module_key'], name='attachments_module__7a3fce_idx'), models.Index(fields=['updated_at'], name='attachments_updated_897bcf_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='attachment',
            constraint=models.UniqueConstraint(fields=('cartilla', 'client_attachment_id'), name='uq_attachment_cartilla_client_id'),
        ),
    ]
