# Generated by Django 4.2.30 on 2026-06-09 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='attachment_type',
            field=models.CharField(choices=[('foto', 'Foto'), ('firma', 'Firma'), ('documento', 'Documento'), ('evidencia', 'Evidencia')], default='foto', max_length=20),
        ),
    ]
